CREATE TABLE qualifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255),
    name       VARCHAR(255),
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by INTEGER,
    CONSTRAINT pk_qualifications PRIMARY KEY (id)
);

DROP TABLE employee_info CASCADE;